/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_simgrid_WRAP_H_
#define SWIG_simgrid_WRAP_H_

struct SwigDirector_BooleanCallback : public BooleanCallback, public Swig::Director {

public:
  void swig_connect_director(JNIEnv* jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
  SwigDirector_BooleanCallback(JNIEnv* jenv);
  virtual void run(bool b);
  virtual ~SwigDirector_BooleanCallback();

public:
  bool swig_overrides(int n) { return (n < 1 ? swig_override[n] : false); }

protected:
  Swig::BoolArray<1> swig_override;
};

struct SwigDirector_ActorCallback : public ActorCallback, public Swig::Director {

public:
  void swig_connect_director(JNIEnv* jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
  SwigDirector_ActorCallback(JNIEnv* jenv);
  virtual void run(simgrid::s4u::Actor* a);
  virtual ~SwigDirector_ActorCallback();

public:
  bool swig_overrides(int n) { return (n < 1 ? swig_override[n] : false); }

protected:
  Swig::BoolArray<1> swig_override;
};

struct SwigDirector_ActorMain : public ActorMain, public Swig::Director {

public:
  void swig_connect_director(JNIEnv* jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
  SwigDirector_ActorMain(JNIEnv* jenv);
  virtual void run();
  virtual ~SwigDirector_ActorMain();

public:
  bool swig_overrides(int n) { return (n < 1 ? swig_override[n] : false); }

protected:
  Swig::BoolArray<1> swig_override;
};

#endif
