#! /bin/sh -e

if test -e gras/trp_tcp_server ; then
  base=gras
else 
  base=.
fi

if [ x = x ] ; then 
  wine=
else
  wine=wine
fi

$wine $base/trp_tcp_server $@ &
sleep 1
$wine $base/trp_tcp_client $@

