/* Copyright (c) 2017-2023. The SimGrid Team. All rights reserved.          */

/* This program is free software; you can redistribute it and/or modify it
 * under the terms of the license (GNU LGPL) which comes with this package. */

#include "simgrid/plugins/chiller.hpp"
#include "simgrid/plugins/energy.h"
#include "simgrid/s4u.hpp"
#include <xbt/log.h>

XBT_LOG_NEW_DEFAULT_CATEGORY(chiller_simple, "Messages specific for this s4u example");
namespace sg4 = simgrid::s4u;

static void manager(simgrid::plugins::ChillerPtr c)
{
  XBT_INFO("Initial state: ");
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());

  XBT_INFO("The machines slowly heat up the room.");
  simgrid::s4u::this_actor::sleep_until(400);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());
  simgrid::s4u::this_actor::sleep_until(800);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());
  simgrid::s4u::this_actor::sleep_until(1000);
  XBT_INFO("The Chiller now compensates the heat generated by the machines.");
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());
  simgrid::s4u::this_actor::sleep_until(1200);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());

  XBT_INFO("Let's compute something.");
  sg4::this_actor::exec_async(1e10);
  simgrid::s4u::this_actor::sleep_until(1250);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());

  simgrid::s4u::this_actor::sleep_until(1300);
  XBT_INFO("Computation done.");

  simgrid::s4u::this_actor::sleep_until(1400);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());

  XBT_INFO("Now let's stress the chiller by decreasing the goal temperature to 23°C.");
  c->set_goal_temp(23);
  simgrid::s4u::this_actor::sleep_until(1600);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());
  simgrid::s4u::this_actor::sleep_until(1800);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());
  simgrid::s4u::this_actor::sleep_until(2000);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());
  simgrid::s4u::this_actor::sleep_until(2200);
  XBT_INFO("%s: Power: %fW T_in: %f°C Energy consumed: %fJ", c->get_cname(), c->get_power(), c->get_temp_in(),
           c->get_energy_consumed());
}

int main(int argc, char* argv[])
{
  sg4::Engine e(&argc, argv);
  e.load_platform(argv[1]);
  sg_host_energy_plugin_init();

  auto chiller = simgrid::plugins::Chiller::init("Chiller", 294, 1006, 0.2, 0.9, 23, 24, 1000);
  chiller->add_host(e.host_by_name("MyHost1"));
  chiller->add_host(e.host_by_name("MyHost2"));
  chiller->add_host(e.host_by_name("MyHost3"));
  sg4::Actor::create("sender", e.host_by_name("MyHost1"), manager, chiller);

  e.run();
  return 0;
}
