#!/bin/sh -e
# Run this to generate all the initial makefiles, etc.

amver=1.9

# AUTOCONF=
# AUTOHEADER=
# AUTOPOINT=
# LIBTOOLIZE=

ACLOCAL="aclocal-$amver -I acmacro" \
AUTOMAKE="automake-$amver" \
  autoreconf -v -i -s || exit 1

echo
echo "And now, please launch ./configure"
echo "----------------------------------"

# What to do the day we declare optional modules using ACI:
#  if test -e aci.conf ; then
#   source aci.conf
#   pass the content of $configure_args to configure

echo 
echo "Most common flags:"
echo "  --enable-maintainer-mode         mandatory if you use the CVS version"
echo "  --disable-compile-optimizations  useful if your gdb gets fooled"
echo

echo 
echo "If you want to compile for several archs from the same (nfs-mounted?) tree, do:"
echo "  mkdir your_arch; cd your_arch && ../configure --srcdir=.."

echo 
echo "(after configure, you'll naturally have to run \`make')"
echo 
echo 
