#!/bin/sh -e
# Run this to generate all the initial makefiles, etc.

amver=1.8

# AUTOCONF=
# AUTOHEADER=
# AUTOPOINT=
# LIBTOOLIZE=

# Add the following to ACLOCAL to use the installed m4 macro about gtk-doc-tools instead of ours
# -I /usr/share/aclocal/gnome2-macros

ACLOCAL="aclocal-$amver -I acmacro" \
AUTOMAKE="automake-$amver" \
  autoreconf -v || exit 1

if test -z "$*"; then
  if test -e aci.conf ; then
    source aci.conf
    echo "**Warning**: I am going to run \`configure' with arguments resulting from aci_configurator execution."
    echo "ie, $configure_args."
    echo "If you wish to pass other ones, please specify them on the"
    echo \`$0\'" command line, or rerun aci_configurator and save the new ones."
    echo
  else
    configure_args="--enable-maintainer-mode --enable-gtk-doc"
    echo "**Warning**: I am going to run \`configure' with the default arguments."
    echo "ie, $configure_args."
    echo "If you wish to pass any to it, please specify them on the"
    echo \`$0\'" command line."
    echo
  fi
else
  configure_args="$@"
  echo "I am going to run \`configure' with the provided arguments."
  echo "ie, $configure_args."
fi

echo "************"
echo "* Running ./configure $configure_args..."
echo "************"
./configure $configure_args || exit 1

echo Now type \`make\' to compile the package


