#!/bin/sh
# Run this to generate all the initial makefiles, etc.

# Copyright (c) 2004-2007. The SimGrid team. All right reserved.

# This file is part of the SimGrid project. This is free software:
# You can redistribute and/or modify it under the terms of the
# GNU LGPL (v2.1) licence.

amversions="${amver:-1.10}"

if [ ! -e bootstrap ] ; then
  if [ -e ../bootstrap ] ; then
    cd ..
  fi
fi

check_version()
{
    eval $2 --version 2>/dev/null | grep -i "$1.*$3" >/dev/null
}

find_version()
{
    tool=$1
    found="NOT_FOUND"
    shift
    versions="$*"

    for version in $versions ; do
	if check_version $tool ${tool}${variant} $version; then
	    found="${version}"
	    echo ${version} >&2
	    break
	fi
    done
    if [ "x$found" = "xNOT_FOUND" ]; then
	found="-" 
    fi
    echo $found
}

amver=`find_version automake ${amversions}`

lt=`which libtoolize`
if [ "x$lt" = "x" ] ; then
  echo "Libtool not found. Please install the libtool package to proceed with a CVS checkout"
  exit 1
fi

am=`which automake-$amver`
if [ "x$am" = "x" ] ; then
  echo "automake versions $amversions not found. Please install the relevant package to proceed with a CVS checkout"
  exit 1
fi

ac=`which autoconf`
if [ "x$ac" = "x" ] ; then
  echo "autoconf not found. Please install the relevant package to proceed with a CVS checkout"
  exit 1
fi

set -e
# AUTOCONF=
# AUTOHEADER=
# AUTOPOINT=
# LIBTOOLIZE=

ACLOCAL="aclocal-$amver -I acmacro" \
AUTOMAKE="automake-$amver" \
  autoreconf -v -i -s || exit 1

echo
echo "And now, please launch ./configure"
echo "----------------------------------"

# What to do the day we declare optional modules using ACI:
#  if test -e aci.conf ; then
#   source aci.conf
#   pass the content of $configure_args to configure

echo 
echo "Most common flags:"
echo "  --enable-maintainer-mode         mandatory if you use the CVS version"
echo "  --disable-compile-optimizations  useful if your gdb gets fooled"
echo

echo 
echo "If you want to compile for several archs from the same (nfs-mounted?) tree, do:"
echo "  mkdir your_arch; cd your_arch && ../configure --srcdir=.."

echo 
echo "(after configure, you'll naturally have to run \`make')"
echo 
echo 
