# CMake generated Testfile for 
# Source directory: /home/mehdi/work/simgrid/simgrid/trunk
# Build directory: /home/mehdi/work/simgrid/simgrid/trunk
# 
# This file replicates the SUBDIRS() and ADD_TEST() commands from the source
# tree CMakeLists.txt file, skipping any SUBDIRS() or ADD_TEST() commands
# that are excluded by CMake control structures, i.e. IF() commands.
ADD_TEST(tesh-self-basic "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "basic.tesh")
ADD_TEST(tesh-self-cd "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/bin" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh/cd.tesh")
ADD_TEST(tesh-self-IO-broken-pipe "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "IO-broken-pipe.tesh")
ADD_TEST(tesh-self-IO-orders "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/bin" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh/IO-orders.tesh")
ADD_TEST(tesh-self-IO-bigsize "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "IO-bigsize.tesh")
ADD_TEST(tesh-self-set-return "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "set-return.tesh")
ADD_TEST(tesh-self-set-signal "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "set-signal.tesh")
ADD_TEST(tesh-self-set-timeout "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "set-timeout.tesh")
ADD_TEST(tesh-self-set-ignore-output "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/bin" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh/set-ignore-output.tesh")
ADD_TEST(tesh-self-catch-return "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/bin" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh/catch-return.tesh")
ADD_TEST(tesh-self-catch-signal "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/bin" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh/catch-signal.tesh")
ADD_TEST(tesh-self-catch-timeout "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/bin" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh/catch-timeout.tesh")
ADD_TEST(tesh-self-catch-wrong-output "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/bin" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh/catch-wrong-output.tesh")
ADD_TEST(tesh-self-bg-basic "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "bg-basic.tesh")
ADD_TEST(tesh-self-bg-set-signal "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "bg-set-signal.tesh")
ADD_TEST(tesh-self-background "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/tools/tesh" "background.tesh")
ADD_TEST(tesh-log-large "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "xbt/log_large_test.tesh")
ADD_TEST(tesh-log-parallel "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "xbt/parallel_log_crashtest.tesh")
ADD_TEST(tesh-gras-dd-mem "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/datadesc/datadesc_mem.tesh")
ADD_TEST(tesh-gras-dd-rw "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/datadesc/datadesc_rw.tesh")
ADD_TEST(tesh-gras-dd-r_little32_4 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/datadesc/datadesc_r_little32_4.tesh")
ADD_TEST(tesh-gras-dd-r_little64 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/datadesc/datadesc_r_little64.tesh")
ADD_TEST(tesh-gras-dd-r_big32_8_4 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/datadesc/datadesc_r_big32_8_4.tesh")
ADD_TEST(tesh-gras-dd-r_big32_8 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/datadesc/datadesc_r_big32_8.tesh")
SET_TESTS_PROPERTIES(tesh-gras-dd-r_big32_8 PROPERTIES  WILL_FAIL "true")
ADD_TEST(tesh-gras-dd-r_big32_2 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/datadesc/datadesc_r_big32_2.tesh")
SET_TESTS_PROPERTIES(tesh-gras-dd-r_big32_2 PROPERTIES  WILL_FAIL "true")
ADD_TEST(tesh-gras-msg_handle-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/msg_handle/test_sg_32")
ADD_TEST(tesh-gras-empty_main-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/empty_main/test_rl")
ADD_TEST(tesh-gras-empty_main-sg "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/empty_main/test_sg")
ADD_TEST(tesh-gras-small_sleep-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "gras/small_sleep/test_sg_32")
ADD_TEST(tesh-msg-get_sender "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "msg/get_sender.tesh")
ADD_TEST(tesh-simdag-reinit_costs "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/network/test_reinit_costs.tesh")
ADD_TEST(tesh-simdag-parser "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/platforms/basic_parsing_test.tesh")
ADD_TEST(tesh-simdag-flatifier "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/platforms/flatifier.tesh")
SET_TESTS_PROPERTIES(tesh-simdag-flatifier PROPERTIES  WILL_FAIL "true")
ADD_TEST(tesh-simdag-basic0 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/basic0.tesh")
ADD_TEST(tesh-simdag-basic1 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/basic1.tesh")
ADD_TEST(tesh-simdag-basic2 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/basic2.tesh")
ADD_TEST(tesh-simdag-basic3 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/basic3.tesh")
ADD_TEST(tesh-simdag-basic4 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/basic4.tesh")
ADD_TEST(tesh-simdag-basic5 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/basic5.tesh")
ADD_TEST(tesh-simdag-basic6 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/basic6.tesh")
ADD_TEST(tesh-simdag-p2p-1 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/network/p2p/test_latency1.tesh")
ADD_TEST(tesh-simdag-p2p-2 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/network/p2p/test_latency2.tesh")
ADD_TEST(tesh-simdag-p2p-3 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/network/p2p/test_latency_bound.tesh")
ADD_TEST(tesh-simdag-mxn-1 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/network/mxn/test_intra_all2all.tesh")
ADD_TEST(tesh-simdag-mxn-2 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/network/mxn/test_intra_independent_comm.tesh")
ADD_TEST(tesh-simdag-mxn-3 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/network/mxn/test_intra_scatter.tesh")
ADD_TEST(tesh-simdag-par-1 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/partask/test_comp_only_seq.tesh")
ADD_TEST(tesh-simdag-par-2 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/teshsuite" "simdag/partask/test_comp_only_par.tesh")
ADD_TEST(gras-ping-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/ping" "test_rl")
ADD_TEST(gras-rpc-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/rpc" "test_rl")
ADD_TEST(gras-spawn-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/spawn" "test_rl")
ADD_TEST(gras-timer-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/timer" "test_rl")
ADD_TEST(gras-chrono-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/chrono" "test_rl")
ADD_TEST(gras-simple_token-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/mutual_exclusion/simple_token" "test_rl")
ADD_TEST(gras-mmrpc-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/mmrpc" "test_rl")
ADD_TEST(gras-all2all-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/all2all" "test_rl")
ADD_TEST(gras-pmm-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/pmm" "test_rl")
ADD_TEST(gras-synchro-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/synchro" "test_rl")
ADD_TEST(gras-properties-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/properties" "test_rl")
ADD_TEST(msg-sendrecv_CLM03 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "sendrecv/sendrecv_CLM03.tesh")
ADD_TEST(msg-sendrecv_Vegas "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "sendrecv/sendrecv_Vegas.tesh")
ADD_TEST(msg-sendrecv_Reno "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "sendrecv/sendrecv_Reno.tesh")
ADD_TEST(msg-suspend "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "suspend/suspend.tesh")
ADD_TEST(msg-masterslave "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "masterslave/masterslave.tesh")
ADD_TEST(msg-masterslave-forwarder "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "masterslave/masterslave_forwarder.tesh")
ADD_TEST(msg-masterslave-failure "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "masterslave/masterslave_failure.tesh")
ADD_TEST(msg-masterslave-bypass "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "masterslave/masterslave_bypass.tesh")
ADD_TEST(msg-masterslave-mailbox "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "masterslave/masterslave_mailbox.tesh")
ADD_TEST(msg-masterslave-vivaldi "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "masterslave/masterslave_vivaldi.tesh")
ADD_TEST(msg-migration "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "migration/migration.tesh")
ADD_TEST(msg-ptask "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "parallel_task/parallel_task.tesh")
ADD_TEST(msg-priority "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "priority/priority.tesh")
ADD_TEST(msg-properties "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "properties/msg_prop.tesh")
ADD_TEST(msg-trace "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "trace/trace.tesh")
ADD_TEST(msg-masterslave_cpu_ti "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg" "masterslave/masterslave_cpu_ti.tesh")
ADD_TEST(gras-ping-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/ping" "test_sg_32")
ADD_TEST(gras-rpc-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/rpc" "test_sg_32")
ADD_TEST(gras-spawn-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/spawn" "test_sg_32")
ADD_TEST(gras-timer-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/timer" "test_sg_32")
ADD_TEST(gras-chrono-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/chrono" "test_sg_32")
ADD_TEST(gras-simple_token-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/mutual_exclusion/simple_token" "test_sg_32")
ADD_TEST(gras-mmrpc-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/mmrpc" "test_sg_32")
ADD_TEST(gras-all2all-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/all2all" "test_sg_32")
ADD_TEST(gras-pmm-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/pmm" "test_sg_32")
ADD_TEST(gras-synchro-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/synchro" "test_sg_32")
ADD_TEST(gras-properties-sg "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/gras/properties" "test_sg")
ADD_TEST(amok-bandwidth-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/amok" "bandwidth/bandwidth_rl.tesh")
SET_TESTS_PROPERTIES(amok-bandwidth-rl PROPERTIES  WILL_FAIL "true")
ADD_TEST(amok-saturate-rl "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/amok" "saturate/saturate_rl.tesh")
SET_TESTS_PROPERTIES(amok-saturate-rl PROPERTIES  WILL_FAIL "true")
ADD_TEST(amok-bandwidth-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/amok" "bandwidth/bandwidth_sg_32.tesh")
ADD_TEST(amok-saturate-sg-32 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/amok" "saturate/saturate_sg_32.tesh")
ADD_TEST(simdag-test_simdag "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/simdag" "test_simdag.tesh")
ADD_TEST(simdag-test_simdag2 "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/simdag" "test_simdag2.tesh")
ADD_TEST(simdag-test_simdag_seq_access "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/simdag" "test_simdag_seq_access.tesh")
ADD_TEST(simdag-test_prop "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/simdag" "properties/test_prop.tesh")
ADD_TEST(simdag-metaxml_test "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/simdag" "metaxml/metaxml_test.tesh")
SET_TESTS_PROPERTIES(simdag-metaxml_test PROPERTIES  WILL_FAIL "true")
ADD_TEST(simdag-minmin_test "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/simdag/scheduling" "test_minmin.tesh")
ADD_TEST(smpi-bcast "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/smpi" "bcast.tesh")
ADD_TEST(smpi-reduce "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/smpi" "reduce.tesh")
ADD_TEST(lua-masterslave "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/lua" "master_slave.tesh")
ADD_TEST(lua-mult_matrix "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/lua" "mult_matrix.tesh")
ADD_TEST(lua-masterslave_bypass "/home/mehdi/work/simgrid/simgrid/trunk/bin/tesh" "--cd" "/home/mehdi/work/simgrid/simgrid/trunk/examples/lua" "master_slave_bypass.tesh")
ADD_TEST(test-xbt-log "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/xbt/log_usage")
ADD_TEST(test-xbt-graphxml "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/xbt/graphxml_usage" "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/xbt/graph.xml")
ADD_TEST(test-xbt-heap "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/xbt/heap_bench")
ADD_TEST(test-surf-lmm "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/lmm_usage")
ADD_TEST(test-surf-maxmin "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/maxmin_bench")
ADD_TEST(test-surf-usage "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/surf_usage" "--cfg=path:/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/" "platform.xml")
ADD_TEST(test-surf_usage2 "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/surf_usage2" "--cfg=path:/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/" "platform.xml")
ADD_TEST(test-surf-trace "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/trace_usage" "--cfg=path:/home/mehdi/work/simgrid/simgrid/trunk/testsuite/surf/")
ADD_TEST(test-simdag-1 "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/simdag/sd_test" "--cfg=path:/home/mehdi/work/simgrid/simgrid/trunk/testsuite/simdag" "small_platform_variable.xml")
ADD_TEST(test-simdag-2 "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/simdag/sd_test" "--cfg=path:/home/mehdi/work/simgrid/simgrid/trunk/testsuite/simdag" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg/small_platform.xml")
ADD_TEST(test-simdag-3 "/home/mehdi/work/simgrid/simgrid/trunk/testsuite/simdag/sd_test" "--cfg=path:/home/mehdi/work/simgrid/simgrid/trunk/testsuite/simdag" "/home/mehdi/work/simgrid/simgrid/trunk/examples/msg/msg_platform.xml")
ADD_TEST(testall "/src/testall")
SUBDIRS(src)
SUBDIRS(tools/gras)
SUBDIRS(tools/tesh)
SUBDIRS(testsuite/xbt)
SUBDIRS(testsuite/surf)
SUBDIRS(testsuite/simdag)
SUBDIRS(teshsuite/xbt)
SUBDIRS(teshsuite/gras/datadesc)
SUBDIRS(teshsuite/gras/msg_handle)
SUBDIRS(teshsuite/gras/empty_main)
SUBDIRS(teshsuite/gras/small_sleep)
SUBDIRS(teshsuite/simdag)
SUBDIRS(teshsuite/simdag/network)
SUBDIRS(teshsuite/simdag/network/p2p)
SUBDIRS(teshsuite/simdag/network/mxn)
SUBDIRS(teshsuite/simdag/partask)
SUBDIRS(teshsuite/simdag/platforms)
SUBDIRS(teshsuite/msg)
SUBDIRS(examples/gras/ping)
SUBDIRS(examples/gras/rpc)
SUBDIRS(examples/gras/spawn)
SUBDIRS(examples/gras/timer)
SUBDIRS(examples/gras/chrono)
SUBDIRS(examples/gras/mutual_exclusion/simple_token)
SUBDIRS(examples/gras/mmrpc)
SUBDIRS(examples/gras/all2all)
SUBDIRS(examples/gras/pmm)
SUBDIRS(examples/gras/synchro)
SUBDIRS(examples/gras/properties)
SUBDIRS(examples/msg/properties)
SUBDIRS(examples/msg/actions)
SUBDIRS(examples/msg/migration)
SUBDIRS(examples/msg/sendrecv)
SUBDIRS(examples/msg/suspend)
SUBDIRS(examples/msg/parallel_task)
SUBDIRS(examples/msg/priority)
SUBDIRS(examples/msg/masterslave)
SUBDIRS(examples/msg/trace)
SUBDIRS(examples/msg/tracing)
SUBDIRS(examples/amok/bandwidth)
SUBDIRS(examples/amok/saturate)
SUBDIRS(examples/simdag)
SUBDIRS(examples/simdag/dax)
SUBDIRS(examples/simdag/metaxml)
SUBDIRS(examples/simdag/properties)
SUBDIRS(examples/simdag/scheduling)
SUBDIRS(examples/smpi)
