include(FindJava)
include(FindJNI)
	
message(STATUS "Looking for jni.h")
if(JAVA_INCLUDE_PATH)
message(STATUS "Looking for jni.h - found")
else(JAVA_INCLUDE_PATH)
message(STATUS "Looking for jni.h - not found")
endif(JAVA_INCLUDE_PATH)

message(STATUS "Looking for jni_md.h")
if(JAVA_INCLUDE_PATH2)
message(STATUS "Looking for jni_md.h - found")
else(JAVA_INCLUDE_PATH2)
message(STATUS "Looking for jni_md.h - not found")
endif(JAVA_INCLUDE_PATH2)

if(JAVA_COMPILE)
message(STATUS "Found javac: ${JAVA_COMPILE}")
else(JAVA_COMPILE)
message(FATAL_ERROR "Not found javac bin")
endif(JAVA_COMPILE)

if(JAVA_ARCHIVE)
message(STATUS "Found jar: ${JAVA_ARCHIVE}")
else(JAVA_ARCHIVE)
message(FATAL_ERROR "Not found jar bin")
endif(JAVA_ARCHIVE)

if(JAVA_INCLUDE_PATH)
	SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}-I${JAVA_INCLUDE_PATH} ")
else(JAVA_INCLUDE_PATH)
	message(STATUS "Need to set JAVA_INCLUDE_PATH to jni.h")
endif(JAVA_INCLUDE_PATH)