/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.simgrid.surf;

public class Resource {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Resource(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Resource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SurfJNI.delete_Resource(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getName() {
    return SurfJNI.Resource_getName(swigCPtr, this);
  }

  public boolean isUsed() {
    return SurfJNI.Resource_isUsed(swigCPtr, this);
  }

  public Model getModel() {
    long cPtr = SurfJNI.Resource_getModel(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public ResourceState getState() {
    return ResourceState.swigToEnum(SurfJNI.Resource_getState(swigCPtr, this));
  }

  public LmmConstraint getConstraint() {
    long cPtr = SurfJNI.Resource_getConstraint(swigCPtr, this);
    return (cPtr == 0) ? null : new LmmConstraint(cPtr, false);
  }

  public XbtDict getProperties() {
    long cPtr = SurfJNI.Resource_getProperties(swigCPtr, this);
    return (cPtr == 0) ? null : new XbtDict(cPtr, false);
  }

  public void updateState(TmgrTraceEvent event_type, double value, double date) {
    SurfJNI.Resource_updateState(swigCPtr, this, TmgrTraceEvent.getCPtr(event_type), event_type, value, date);
  }

}
