if(enable_memcheck)

# teshsuite/xbt
ADD_TEST(memcheck-tesh-log-large-0 xbt/log_large_test --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-log-large-1 xbt/log_large_test --log=root.fmt:%m%n  --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-log-parallel-0 xbt/parallel_log_crashtest --log=root.fmt:%m%n  --cd ${PROJECT_DIRECTORY}/teshsuite/)

# teshsuite/gras/datadesc directory
ADD_TEST(memcheck-tesh-gras-dd-mem-0 gras/datadesc/datadesc_usage --copy --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-rw-0 rm -f datadesc_usage.out --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-rw-1 gras/datadesc/datadesc_usage --write --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-rw-2 gras/datadesc/datadesc_usage --read --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-r_little32_4-0 gras/datadesc/datadesc_usage --read ./gras/datadesc/datadesc.little32_4 --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-r_little64-0 gras/datadesc/datadesc_usage --read ./gras/datadesc/datadesc.little64 --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-r_big32_8_4-0 gras/datadesc/datadesc_usage --read ./gras/datadesc/datadesc.big32_8_4 --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-r_big32_8-0 gras/datadesc/datadesc_usage --read ./gras/datadesc/datadesc.big32_8 --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-gras-dd-r_big32_2-0 gras/datadesc/datadesc_usage --read ./gras/datadesc/datadesc.big32_2 --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/teshsuite/)

IF(${ARCH_32_BITS})
ADD_TEST(memcheck-tesh-gras-msg_handle-sg-32-0 gras/msg_handle/msg_handle_simulator ./../examples/msg/small_platform.xml ./gras/msg_handle/msg_handle.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ELSE(${ARCH_32_BITS})
ADD_TEST(memcheck-tesh-gras-msg_handle-sg-64-0 gras/msg_handle/msg_handle_simulator ./../examples/msg/small_platform.xml ./gras/msg_handle/msg_handle.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ENDIF(${ARCH_32_BITS})

ADD_TEST(memcheck-tesh-gras-empty_main-sg-0 ./gras/empty_main/empty_main_simulator ./../examples/msg/small_platform.xml ./gras/empty_main/empty_main.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)

IF(${ARCH_32_BITS})
ADD_TEST(memcheck-tesh-gras-small_sleep-sg-32-0 ./gras/small_sleep/small_sleep_simulator ./../examples/msg/small_platform.xml ./gras/small_sleep/small_sleep.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ELSE(${ARCH_32_BITS})
ADD_TEST(memcheck-tesh-gras-small_sleep-sg-64-0 ./gras/small_sleep/small_sleep_simulator ./../examples/msg/small_platform.xml ./gras/small_sleep/small_sleep.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ENDIF(${ARCH_32_BITS})

ADD_TEST(memcheck-tesh-simdag-reinit_costs-0 simdag/network/test_reinit_costs ./simdag/network/platform_2p_1sl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-0 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_cluster_foreach.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-1 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_cluster_one_host_random.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-2 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_cluster_one_host.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-3 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_cluster_properties_foreach.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-4 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_cluster.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-5 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_host_availability.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-6 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_host_properties.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-7 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_host_state_file.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-8 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_host_state_off.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-9 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_host_state_on.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-10 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_host_trace_inside.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-11 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_host.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-12 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_link_availability.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-13 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_link_fatpipe.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-14 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_link_shared.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-15 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms one_link_state_file.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-16 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms three_hosts_non_symmetric_route.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-17 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms two_clusters_symmetric.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-18 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms two_clusters.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-19 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms two_hosts_multi_hop.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-parser-20 simdag/platforms/basic_parsing_test --log=xbt_cfg.thres:critical --cfg=path:./simdag/platforms two_hosts_one_link.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-0 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_cluster.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-1 false --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-2 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_cluster_foreach.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-3 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_cluster_one_host_random.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-4 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_cluster_one_host.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-5 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_cluster_properties_foreach.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-6 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_cluster_properties_override.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-7 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host_availability.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-8 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host_properties.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-9 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host_state_file.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-10 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host_state_off.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-11 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host_state_on.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-12 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host_trace_file.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-13 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host_trace_inside.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-14 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_host.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-15 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_link_availability.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-16 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_link_fatpipe.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-17 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_link_shared.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-18 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ one_link_state_file.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-19 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ route_override.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-20 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ three_hosts_non_symmetric_route.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-21 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ two_clusters_symmetric.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-22 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ two_clusters.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-23 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ two_hosts_multi_hop.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-flatifier-24 ./simdag/platforms/flatifier --cfg=path:./simdag/platforms/ two_hosts_one_link.xml --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-basic0-0 simdag/basic0 ./simdag/basic_platform.xml --surf-path=${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-basic1-0 simdag/basic1 ./simdag/basic_platform.xml --surf-path=${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-basic2-0 simdag/basic2 ./simdag/basic_platform.xml --surf-path=${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-basic3-0 simdag/basic3 ./simdag/basic_platform.xml --surf-path=${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-basic4-0 simdag/basic4 ./simdag/basic_platform.xml --surf-path=${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-basic5-0 simdag/basic5 ./simdag/basic_platform.xml --surf-path=${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-basic6-0 simdag/basic6 ./simdag/network/p2p/platform_2p_1sl.xml --surf-path=${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-1-0 simdag/network/p2p/test_latency1 ./simdag/network/p2p/platform_2p_1sl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-1-1 simdag/network/p2p/test_latency1 ./simdag/network/p2p/platform_2p_1fl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-1-2 simdag/network/p2p/test_latency1 ./simdag/network/p2p/platform_2p_1switch.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-2-0 simdag/network/p2p/test_latency2 ./simdag/network/p2p/platform_2p_1sl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-2-1 simdag/network/p2p/test_latency2 ./simdag/network/p2p/platform_2p_1fl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-2-2 simdag/network/p2p/test_latency2 ./simdag/network/p2p/platform_2p_1switch.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-3-0 simdag/network/p2p/test_latency3 ./simdag/network/p2p/platform_2p_1sl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-3-1 simdag/network/p2p/test_latency3 ./simdag/network/p2p/platform_2p_1fl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-3-2 simdag/network/p2p/test_latency3 ./simdag/network/p2p/platform_2p_1switch.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-p2p-3-0 simdag/network/p2p/test_latency_bound ./simdag/network/p2p/platform_2p_1bb.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-mxn-1-0 simdag/network/mxn/test_intra_all2all ./simdag/network/mxn/platform_4p_1switch.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-mxn-2-0 simdag/network/mxn/test_intra_independent_comm ./simdag/network/mxn/platform_4p_1switch.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-mxn-3-0 simdag/network/mxn/test_intra_scatter ./simdag/network/mxn/platform_4p_1switch.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-par-1-0 simdag/partask/test_comp_only_seq ./simdag/partask/platform_2p_1sl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-par-2-0 simdag/partask/test_comp_only_par ./simdag/partask/platform_2p_1sl.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)
ADD_TEST(memcheck-tesh-simdag-par-2-1 simdag/partask/test_comp_only_par ./simdag/partask/platform_2p_1sl_hetero.xml --surf-path=${PROJECT_DIRECTORY}/src --log=sd_kernel.thres=warning --cd ${PROJECT_DIRECTORY}/teshsuite/)

# GRAS examples
ADD_TEST(memcheck-gras-spawn-rl-0 ./spawn_father 4602 5 --log=root.fmt=%m%n --cd ${PROJECT_DIRECTORY}/examples/gras/spawn/)
ADD_TEST(memcheck-gras-timer-rl-0 ./timer_client --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/examples/gras/timer/)
ADD_TEST(memcheck-gras-chrono-rl-0 ./chrono_multiplier --log=root.fmt:%m%n --cd ${PROJECT_DIRECTORY}/examples/gras/chrono/)
ADD_TEST(memcheck-gras-synchro-rl-0 ./synchro_philosopher 4 --log=root.fmt=%m%n --cd ${PROJECT_DIRECTORY}/examples/gras/synchro/)
ADD_TEST(memcheck-gras-properties-rl-0 ./properties_alice --log=root.fmt=%P:%t%e%m%n --cd ${PROJECT_DIRECTORY}/examples/gras/properties/)
ADD_TEST(memcheck-gras-properties-rl-1 ./properties_bob --log=root.fmt=%P:%t%e%m%n --cd ${PROJECT_DIRECTORY}/examples/gras/properties/)

# MSG examples
ADD_TEST(memcheck-msg-sendrecv_CLM03-0 sendrecv/sendrecv ./sendrecv/platform_sendrecv.xml ./sendrecv/deployment_sendrecv.xml --cfg=workstation/model:CLM03 --cfg=cpu/model:Cas01 --cfg=network/model:CM02 --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-sendrecv_Vegas-0 sendrecv/sendrecv ./sendrecv/platform_sendrecv.xml ./sendrecv/deployment_sendrecv.xml "--cfg=workstation/model:compound cpu/model:Cas01 network/model:Vegas" --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-sendrecv_Reno-0 sendrecv/sendrecv ./sendrecv/platform_sendrecv.xml ./sendrecv/deployment_sendrecv.xml "--cfg=workstation/model:compound cpu/model:Cas01 network/model:Reno" --log=surf_lagrange.thres=critical --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-suspend-0 suspend/suspend ./msg_platform.xml ./suspend/deployment_suspend.xml  --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave-0 masterslave/masterslave_forwarder ./small_platform_with_routers.xml ./masterslave/deployment_masterslave.xml --trace --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave-forwarder-0 masterslave/masterslave_forwarder ./msg_platform.xml ./masterslave/deployment_masterslave_forwarder.xml  --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave-failure-0 masterslave/masterslave_failure --log=xbt_cfg.thres:critical --log=no_loc ./small_platform_with_failures.xml ./masterslave/deployment_masterslave.xml --cfg=path:${PROJECT_DIRECTORY}/src --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave-bypass-0 masterslave/masterslave_bypass --log=no_loc  --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave-mailbox-0 masterslave/masterslave_mailbox ./small_platform_with_routers.xml ./masterslave/deployment_masterslave_mailbox.xml --trace --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave-vivaldi-0 ./masterslave/masterslave_mailbox --cfg=network/model:Vivaldi ../platforms/vivaldi.xml ./masterslave/deployment_masterslave_vivaldi.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-migration-0 migration/migration ./msg_platform.xml ./migration/migration.deploy  --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-ptask-0 parallel_task/parallel_task ./small_platform.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-ptask-1 parallel_task/test_ptask ./parallel_task/test_ptask_platform.xml ./parallel_task/test_ptask_deployment.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-priority-0 priority/priority ./small_platform.xml  ./priority/deployment_priority.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-properties-0 properties/msg_prop ./../platforms/prop.xml ./properties/deployment_properties.xml  --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-0 trace/test_trace_integration ./trace/test1.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-1 trace/test_trace_integration ./trace/test2.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-2 trace/test_trace_integration ./trace/test3.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-3 trace/test_trace_integration ./trace/test4.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-4 trace/test_trace_integration ./trace/test5.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-5 trace/test_trace_integration ./trace/test6.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-6 trace/test_trace_integration ./trace/test7.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-7 trace/test_trace_integration ./trace/test8.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-8 trace/test_trace_integration ./trace/test9.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-9 trace/test_trace_integration ./trace/test10.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-trace-10 trace/test_trace_integration ./trace/test11.xml --cfg=workstation/model:compound --cfg=network/model:CM02 --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave_cpu_ti-0 masterslave/masterslave_forwarder ./small_platform.xml ./masterslave/deployment_masterslave.xml --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave_cpu_ti-1 masterslave/masterslave_forwarder ./msg_platform.xml ./masterslave/deployment_masterslave_forwarder.xml --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave_cpu_ti-2 masterslave/masterslave_failure --log=xbt_cfg.thres:critical --log=no_loc ./small_platform_with_failures.xml ./masterslave/deployment_masterslave.xml --cfg=path:${PROJECT_DIRECTORY}/src --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-masterslave_cpu_ti-3 masterslave/masterslave_bypass --log=no_loc --cfg=cpu/model:CpuTI --cd ${PROJECT_DIRECTORY}/examples/msg/)

IF(HAVE_TRACING)
ADD_TEST(memcheck-tracing-ms-0 tracing/ms ./tracing/platform.xml ./tracing/deployment.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-tracing-ms-1 cat ./tracing/../ms.trace --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-tracing-categories-0 tracing/categories ./tracing/platform.xml ./tracing/deployment.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-tracing-categories-1 cat ./tracing/../categories.trace --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-tracing-volume-0 tracing/volume ./tracing/platform.xml ./tracing/deployment.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-tracing-tasks-0 tracing/tasks ./tracing/platform.xml ./tracing/deployment.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-tracing-process-migration-0 tracing/procmig ./tracing/platform.xml ./tracing/procmig-deploy.xml --cd ${PROJECT_DIRECTORY}/examples/msg/)
ENDIF(HAVE_TRACING)

IF(${ARCH_32_BITS})
ADD_TEST(memcheck-gras-ping-sg-32-0 ./ping_simulator ./../../msg/small_platform.xml ./ping.xml --cd ${PROJECT_DIRECTORY}/examples/gras/ping/)
ADD_TEST(memcheck-gras-rpc-sg-32-0 ./rpc_simulator ./../../msg/small_platform.xml ./rpc.xml --log=root.fmt:"'[%h:%P:(%i)] [%c/%p] %m%n'" --cd ${PROJECT_DIRECTORY}/examples/gras/rpc/)
ADD_TEST(memcheck-gras-spawn-sg-32-0 ./spawn_simulator ./../../msg/small_platform.xml ./spawn.xml --cd ${PROJECT_DIRECTORY}/examples/gras/spawn/)
ADD_TEST(memcheck-gras-timer-sg-32-0 ./timer_simulator ./../../msg/small_platform.xml ./timer.xml --cd ${PROJECT_DIRECTORY}/examples/gras/timer/)
ADD_TEST(memcheck-gras-chrono-sg-32-0 ./chrono_simulator ./../../msg/small_platform.xml ./chrono.xml --cd ${PROJECT_DIRECTORY}/examples/gras/chrono/)
ADD_TEST(memcheck-gras-simple_token-sg-32-0 ./simple_token_simulator ./../../../msg/small_platform.xml ./simple_token.xml  --cd ${PROJECT_DIRECTORY}/examples/gras/mutual_exclusion/simple_token/)
ADD_TEST(memcheck-gras-mmrpc-sg-32-0 ./mmrpc_simulator ./../../msg/small_platform.xml ./mmrpc.xml --cd ${PROJECT_DIRECTORY}/examples/gras/mmrpc/)
ADD_TEST(memcheck-gras-all2all-sg-32-0 ./all2all_simulator ./../../msg/small_platform.xml ./all2all.xml --cd ${PROJECT_DIRECTORY}/examples/gras/all2all/)
ADD_TEST(memcheck-gras-pmm-sg-32-0 ./pmm_simulator ./../../msg/msg_platform.xml ./pmm.xml --cd ${PROJECT_DIRECTORY}/examples/gras/pmm/)
ADD_TEST(memcheck-gras-synchro-sg-32-0 ./synchro_simulator ./../../msg/small_platform.xml ./synchro.xml --cd ${PROJECT_DIRECTORY}/examples/gras/synchro/)
ELSE(${ARCH_32_BITS})
ADD_TEST(memcheck-gras-ping-sg-64-0 ./ping_simulator ./../../msg/small_platform.xml ./ping.xml --cd ${PROJECT_DIRECTORY}/examples/gras/ping/)
ADD_TEST(memcheck-gras-rpc-sg-64-0 ./rpc_simulator ./../../msg/small_platform.xml ./rpc.xml --log=root.fmt:"'[%h:%P:(%i)] [%c/%p] %m%n'" --cd ${PROJECT_DIRECTORY}/examples/gras/rpc/)
ADD_TEST(memcheck-gras-spawn-sg-64-0 ./spawn_simulator ./../../msg/small_platform.xml ./spawn.xml --cd ${PROJECT_DIRECTORY}/examples/gras/spawn/)
ADD_TEST(memcheck-gras-timer-sg-64-0 ./timer_simulator ./../../msg/small_platform.xml ./timer.xml --cd ${PROJECT_DIRECTORY}/examples/gras/timer/)
ADD_TEST(memcheck-gras-chrono-sg-64-0 ./chrono_simulator ./../../msg/small_platform.xml ./chrono.xml --cd ${PROJECT_DIRECTORY}/examples/gras/chrono/)
ADD_TEST(memcheck-gras-simple_token-sg-64-0 ./simple_token_simulator ./../../../msg/small_platform.xml ./simple_token.xml  --cd ${PROJECT_DIRECTORY}/examples/gras/mutual_exclusion/simple_token/)
ADD_TEST(memcheck-gras-mmrpc-sg-64-0 ./mmrpc_simulator ./../../msg/small_platform.xml ./mmrpc.xml --cd ${PROJECT_DIRECTORY}/examples/gras/mmrpc/)
ADD_TEST(memcheck-gras-all2all-sg-64-0 ./all2all_simulator ./../../msg/small_platform.xml ./all2all.xml --cd ${PROJECT_DIRECTORY}/examples/gras/all2all/)
ADD_TEST(memcheck-gras-pmm-sg-64-0 ./pmm_simulator ./../../msg/msg_platform.xml ./pmm.xml --cd ${PROJECT_DIRECTORY}/examples/gras/pmm/)
ADD_TEST(memcheck-gras-synchro-sg-64-0 ./synchro_simulator ./../../msg/small_platform.xml ./synchro.xml --cd ${PROJECT_DIRECTORY}/examples/gras/synchro/)
ENDIF(${ARCH_32_BITS})
ADD_TEST(memcheck-gras-properties-sg-0 ./properties_simulator ./../../platforms/prop.xml ./properties.xml --cd ${PROJECT_DIRECTORY}/examples/gras/properties/)

# amok examples
IF(${ARCH_32_BITS})
ADD_TEST(memcheck-amok-bandwidth-sg-32-0 bandwidth/bandwidth_simulator ./../msg/small_platform.xml ./bandwidth/bandwidth.xml --cd ${PROJECT_DIRECTORY}/examples/amok/)
ADD_TEST(memcheck-amok-saturate-sg-32-0 saturate/saturate_simulator ./../msg/small_platform.xml ./saturate/saturate.xml --cd ${PROJECT_DIRECTORY}/examples/amok/)
ELSE(${ARCH_32_BITS})
ADD_TEST(memcheck-amok-bandwidth-sg-64-0 bandwidth/bandwidth_simulator ./../msg/small_platform.xml ./bandwidth/bandwidth.xml --cd ${PROJECT_DIRECTORY}/examples/amok/)
ADD_TEST(memcheck-amok-saturate-sg-64-0 saturate/saturate_simulator ./../msg/small_platform.xml ./saturate/saturate.xml --cd ${PROJECT_DIRECTORY}/examples/amok/)
ENDIF(${ARCH_32_BITS})

# simdag examples
ADD_TEST(memcheck-simdag-test_simdag-0 ./sd_test ./../msg/msg_platform.xml --cd ${PROJECT_DIRECTORY}/examples/simdag/)
ADD_TEST(memcheck-simdag-test_simdag2-0 ./sd_test2 ./2clusters.xml --cd ${PROJECT_DIRECTORY}/examples/simdag/)
ADD_TEST(memcheck-simdag-test_prop-0 properties/sd_prop ./../platforms/prop.xml --cd ${PROJECT_DIRECTORY}/examples/simdag/)
ADD_TEST(memcheck-simdag-metaxml_test-0 metaxml/sd_meta ./../platforms/metaxml.xml --cd ${PROJECT_DIRECTORY}/examples/simdag/)

if(enable_smpi)
# smpi examples
ADD_TEST(memcheck-smpi-bcast-0 ${CMAKE_BINARY_DIR}/bin/smpirun -map -hostfile ./hostfile -platform ./../msg/small_platform.xml -np 3 ./bcast -q --cd ${PROJECT_DIRECTORY}/examples/smpi/)
ADD_TEST(memcheck-smpi-bcast-1 ${CMAKE_BINARY_DIR}/bin/smpirun -map -hostfile ./hostfile -platform ./../msg/small_platform.xml -np 6 ./bcast -q --cd ${PROJECT_DIRECTORY}/examples/smpi/)
ADD_TEST(memcheck-smpi-bcast-2 ${CMAKE_BINARY_DIR}/bin/smpirun -map -hostfile ./hostfile -platform ./../msg/small_platform.xml -np 12 ./bcast -q --cd ${PROJECT_DIRECTORY}/examples/smpi/)
ADD_TEST(memcheck-smpi-reduce-0 ${CMAKE_BINARY_DIR}/bin/smpirun -map -hostfile ./hostfile -platform ./../msg/small_platform.xml -np 3 ./reduce -q --cd ${PROJECT_DIRECTORY}/examples/smpi/)
ADD_TEST(memcheck-smpi-reduce-1 ${CMAKE_BINARY_DIR}/bin/smpirun -map -hostfile ./hostfile -platform ./../msg/small_platform.xml -np 6 ./reduce -q --cd ${PROJECT_DIRECTORY}/examples/smpi/)
ADD_TEST(memcheck-smpi-reduce-2 ${CMAKE_BINARY_DIR}/bin/smpirun -map -hostfile ./hostfile -platform ./../msg/small_platform.xml -np 12 ./reduce -q  --cd ${PROJECT_DIRECTORY}/examples/smpi/)
endif(enable_smpi)

if(HAVE_GTNETS)
ADD_TEST(memcheck-msg-gtnets-waxman-0 gtnets/gtnets gtnets/waxman-p.xml gtnets/waxman-d.xml --cfg=workstation/model:compound --cfg=cpu/model:Cas01 --cfg=network/model:GTNets --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-gtnets-dogbone-0 gtnets/gtnets gtnets/dogbone-p.xml gtnets/dogbone-d.xml --cfg=workstation/model:compound --cfg=cpu/model:Cas01 --cfg=network/model:GTNets --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-gtnets-onelink-0 gtnets/gtnets gtnets/onelink-p.xml gtnets/onelink-d.xml --cfg=workstation/model:compound --cfg=cpu/model:Cas01 --cfg=network/model:GTNets --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-gtnets-dogbone-lv08-0 gtnets/gtnets gtnets/dogbone-p.xml gtnets/dogbone-d.xml --cfg=workstation/model:compound --cfg=cpu/model:Cas01 --cfg=network/model:LV08 --cd ${PROJECT_DIRECTORY}/examples/msg/)
ADD_TEST(memcheck-msg-gtnets-onelink-lv08-0 gtnets/gtnets gtnets/onelink-p.xml gtnets/onelink-d.xml --cfg=workstation/model:compound --cfg=cpu/model:Cas01  --cfg=network/model:LV08 2>&1 | grep --color=auto -v root/INFO | grep -v simix_network/INFO --cd ${PROJECT_DIRECTORY}/examples/msg/)
endif(HAVE_GTNETS)

# Lua examples
if(HAVE_LUA)
ADD_TEST(memcheck-lua-masterslave-0 lua master_slave.lua --cd ${PROJECT_DIRECTORY}/examples/lua/)
ADD_TEST(memcheck-lua-mult_matrix-0 lua mult_matrix.lua --cd ${PROJECT_DIRECTORY}/examples/lua/)
endif(HAVE_LUA)

# Ruby examples
if(HAVE_RUBY)
ADD_TEST(memcheck-ruby-masterslave-0 ruby -I../../src/bindings/ruby MasterSlave.rb --cd ${PROJECT_DIRECTORY}/examples/ruby/)
ADD_TEST(memcheck-ruby-ping_pong-0 ruby -I ../../src/bindings/ruby PingPong.rb --cd ${PROJECT_DIRECTORY}/examples/ruby/)
ADD_TEST(memcheck-ruby-quicksort-0 ruby -I ../../src/bindings/ruby Quicksort.rb --cd ${PROJECT_DIRECTORY}/examples/ruby/)
endif(HAVE_RUBY)

endif(enable_memcheck)
