/**********************************************************************/
/* File generated by src/simix/simcalls.py from src/simix/simcalls.in */
/*                                                                    */
/*                    DO NOT EVER CHANGE THIS FILE                    */
/*                                                                    */
/* change simcalls specification in src/simix/simcalls.in             */
/* Copyright (c) 2014-2020. The SimGrid Team. All rights reserved.    */
/**********************************************************************/

/*
 * Note that the name comes from http://en.wikipedia.org/wiki/Popping
 * Indeed, the control flow is doing a strange dance in there.
 *
 * That's not about http://en.wikipedia.org/wiki/Poop, despite the odor :)
 */

/**
 * @brief All possible simcalls.
 */
typedef enum {
  SIMCALL_NONE,
  SIMCALL_EXECUTION_WAIT,
  SIMCALL_EXECUTION_WAITANY_FOR,
  SIMCALL_COMM_SEND,
  SIMCALL_COMM_ISEND,
  SIMCALL_COMM_RECV,
  SIMCALL_COMM_IRECV,
  SIMCALL_COMM_WAITANY,
  SIMCALL_COMM_WAIT,
  SIMCALL_COMM_TEST,
  SIMCALL_COMM_TESTANY,
  SIMCALL_MUTEX_LOCK,
  SIMCALL_MUTEX_TRYLOCK,
  SIMCALL_MUTEX_UNLOCK,
  SIMCALL_COND_WAIT,
  SIMCALL_COND_WAIT_TIMEOUT,
  SIMCALL_SEM_ACQUIRE,
  SIMCALL_SEM_ACQUIRE_TIMEOUT,
  SIMCALL_IO_WAIT,
  SIMCALL_MC_RANDOM,
  SIMCALL_RUN_KERNEL,
  SIMCALL_RUN_BLOCKING,
  NUM_SIMCALLS
} e_smx_simcall_t;
