/* Copyright (c) 2008-2020. The SimGrid Team. All rights reserved.          */

/* This program is free software; you can redistribute it and/or modify it
 * under the terms of the license (GNU LGPL) which comes with this package. */

#ifndef SIMGRID_MC_REPLAY_H
#define SIMGRID_MC_REPLAY_H

#include "src/mc/mc_config.hpp"

/** Replay path (if any) in string representation
 *
 *  This is using the format generated by traceToString().
 */
#define MC_record_path (_sg_mc_record_path.get())

/** Whether the replay mode is enabled */
static inline int MC_record_replay_is_active()
{
  return not MC_record_path.empty();
}

#endif
