#! /bin/sh

if test "x$DO_NOT_HAVE_JAVA" = x1 ; then
  exit 77
fi

t=`basename $1 .class`

# uncomment this when JNI becomes mad
# options="-verbose:jni -Xcheck:jni "

echo "(LD_LIBRARY_PATH=$LD_LIBRARY_PATH)"
echo "(CLASSPATH=$CLASSPATH)"
echo java $options $t *platform.xml *deployment.xml
java $options $t *platform.xml *deployment.xml
