.TH smpiff 1
.SH NAME
smpiff \- SMPI Fortran 77 wrapper compiler
.SH SYNOPSIS
smpiff …
.SH DESCRIPTION
smpiff is a wrapper around the Fortran 77 compiler defined when building SimGrid, adding the right flags in order to use the SimGrid library and SMPI, the MPI implementation within it.  Most of the arguments filled to smpiff will be passed to the underlying compiler directly, except for \fB\-\-version\fR which gives the SimGrid library version, and \fB\-\-compiler-version\fR which gives the F77 compiler version. Please refer to the latter documentation in case of trouble.
.SH ENVIRONMENT VARIABLES
All environment variables taken into account by the underlying compiler will be used, but note that the compiler can not be modified.
.SH AUTHORS
The SimGrid team (simgrid-devel@lists.gforge.inria.fr)
.SH COPYRIGHT AND LICENCE
Copyright (c) 2014. The SimGrid Team. All rights reserved.

This program is free software; you may redistribute it and/or modify it under the terms of GNU LGPL (v2.1) license.
.SH SEE ALSO
.BR smpirun (1),
.BR smpicc (1),
.BR smpicxx (1),
.BR smpif90 (1)
