#! /bin/sh

HTML="buildlogs/index.html"
rm -f $HTML

echo "<html>" >> $HTML
for VERSION in `ls buildlogs|grep -v html` ; do
  echo "XXXX Version $VERSION"
  echo "<h3>$VERSION</h3><table border=1>" >> $HTML
  for file in `ls buildlogs/$VERSION/*.log`; do
    file=`basename $file`
    host=`basename $file .log`
    
    ## Extract the output from config.log
    cat buildlogs/$VERSION/$file | \
      sed -e ':begin' \
          -e '/CONFIG-LOG-DUMP-BEGIN/ { ' \
	  -e '  :in' \
	  -e '  n'\
	  -e '  /CONFIG-LOG-DUMP-END/Q' \
	  -e '  p'\
	  -e '  b in' \
	  -e '}'\
	  -e 'n'\
	  -e 'b begin' \
	  -n \
       >buildlogs/$VERSION/$host.config
    cat buildlogs/$VERSION/$file | \
      sed -e ':begin' \
          -e '/CONFIG-LOG-DUMP-BEGIN/Q'\
	  -e 'p'\
	  -e 'n'\
	  -e 'b begin' \
	  -n \
       >buildlogs/$VERSION/$host.output

    ## Extract some info out there
    last=`tail -n 1 buildlogs/$VERSION/$file`
    sys=`grep -e "^build='[^']*'\$" buildlogs/$VERSION/$file| \
	 sed "s/^build='\([^']*\)'\$/\1/"`
    grassys=`grep "^#define GRAS_THISARCH" buildlogs/$VERSION/$file| \
             sed 's/.*GRAS_THISARCH //'`

	 
    ## Make text and html outputs
    if [ "x$last" = "xRemote compilation sucessful." ] ; then
      res="success: "
      color=
    else
      res="FAILED:  "
      color="#fc5e5e"
    fi
    echo "<tr <td><a href=$VERSION/$host.output>$res</a>" >> $HTML
    echo "    <td bgcolor='$color'>$host"                 >> $HTML
    echo "    <td><a href=$VERSION/$host.config>$sys</a>" >> $HTML
    
    echo "$res $host     $sys ($grassys)"
  done
  echo "</table>" >> $HTML
done
echo "</html>" >>$HTML
