/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.simgrid.s4u;

public class FatTreeParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FatTreeParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FatTreeParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FatTreeParams obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        simgridJNI.delete_FatTreeParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLevels(long value) {
    simgridJNI.FatTreeParams_levels_set(swigCPtr, this, value);
  }

  public long getLevels() {
    return simgridJNI.FatTreeParams_levels_get(swigCPtr, this);
  }

  public void setDown(SWIGTYPE_p_std__vectorT_unsigned_int_t value) {
    simgridJNI.FatTreeParams_down_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t getDown() {
    long cPtr = simgridJNI.FatTreeParams_down_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_unsigned_int_t(cPtr, false);
  }

  public void setUp(SWIGTYPE_p_std__vectorT_unsigned_int_t value) {
    simgridJNI.FatTreeParams_up_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t getUp() {
    long cPtr = simgridJNI.FatTreeParams_up_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_unsigned_int_t(cPtr, false);
  }

  public void setNumber(SWIGTYPE_p_std__vectorT_unsigned_int_t value) {
    simgridJNI.FatTreeParams_number_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t getNumber() {
    long cPtr = simgridJNI.FatTreeParams_number_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_unsigned_int_t(cPtr, false);
  }

  public FatTreeParams(long n_levels, SWIGTYPE_p_std__vectorT_unsigned_int_t down_links, SWIGTYPE_p_std__vectorT_unsigned_int_t up_links, SWIGTYPE_p_std__vectorT_unsigned_int_t links_number) {
    this(simgridJNI.new_FatTreeParams(n_levels, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(down_links), SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(up_links), SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(links_number)), true);
  }

}
