# Base image 
FROM simgrid/stable

# - Clone simgrid-template-s4u, as it is needed by the tutorial
RUN apt update && apt install -y pajeng r-base r-cran-ggplot2 r-cran-dplyr cmake g++ git libboost-all-dev&& \
    cd /source && \
    git clone --depth=1 https://framagit.org/simgrid/simgrid-template-s4u.git simgrid-template-s4u.git && \
    apt autoremove -y && apt clean && apt autoclean