# Base image 
FROM debian:testing

# - Install SimGrid's dependencies
RUN apt update && \
    apt install -y \
       g++ gcc gfortran default-jdk \
       git \
       valgrind \
       libboost-dev libboost-all-dev \
       cmake \
       python3-pip \
       doxygen fig2dev \
       chrpath \
       libdw-dev libevent-dev libunwind8-dev
		   